#!/bin/bash

echo "🔧 临时禁用所有扩展进行测试..."
echo ""
echo "📋 操作步骤："
echo ""
echo "1️⃣ 在 Cursor 中按 Cmd+Shift+P"
echo "2️⃣ 输入: Developer: Reload Window with Extensions Disabled"
echo "3️⃣ 选择这个选项"
echo ""
echo "✅ Cursor 会重新加载，但所有扩展都会被临时禁用"
echo ""
echo "🧪 测试方法："
echo "   - 切换几个不同的 AI 对话"
echo "   - 看看是否还会出现'闪到底部再跳到顶部'的问题"
echo ""
echo "📊 判断结果："
echo ""
echo "✅ 如果问题消失了 → 说明是某个扩展导致的"
echo "   → 执行下一步：逐个启用扩展找出罪魁祸首"
echo ""
echo "❌ 如果问题依然存在 → 说明是 Cursor 本身的 bug"
echo "   → 执行清除缓存或更新 Cursor"
echo ""
echo "🔄 恢复扩展："
echo "   - 再次按 Cmd+Shift+P"
echo "   - 输入: Developer: Reload Window"
echo "   - 扩展会重新启用"
echo ""

